meta_data:
  version: "1.0"
  description: "Base config file for training RotNet self supervised classifier model using a selected directory of images"

defaults: 
  model_name: &model_name mask_rcnn
  step: &step 11
  seed: &seed 42
  device: &device "cuda:0"

loops:
  device: *device
  grad_acc: 1
  start: 0
  end: 3
  seed: *seed

logs:
  model_name: *model_name
  logger_type: basic
  print_freq: 10
  iter_init: 0
  best_init: [.inf, 0]
  step: *step
  exp_dir: "Mask_RCNN_Jigsaw/AWL"
  sub_dir: "model_2"
  last_title: last_model.pth
  best_post_title: post_best.pth
  best_pre_title: pre_best.pth

model:
  model_name: *model_name
  device: *device
  load_model: outputs/models/Mask_RCNN_Jigsaw/AWL/model_2/post_best.pth
  params:
    ssl_pt: false
    backbone_type: pre-trained
    trainable_layers: 5
    num_classes: 2
    hidden_layers: 256
    drop_out: 0.5
    min_size: 800
    max_size: 1333
    device: *device

dataset:
  source: data_handling/sources/jersey_dataset_v4
  random_seed: *seed
  model_name: *model_name
  col_fn: true
  params:
    train:
      dir: train
      json: train.json
      batch_size: 1
      shuffle: true
      num_workers: 0
      augmentations: true
    val:
      dir: val
      json: val.json
      batch_size: 1
      shuffle: false
      num_workers: 0
      augmentations: false
    test:
      dir: test
      json: test.json
      batch_size: 1
      shuffle: false
      num_workers: 0
      augmentations: false

losses:
  model_name: *model_name
  params: 
    awl: false

optimiser:
  model_name: *model_name
  opt_name: "Adam"
  opt_params:
    lr: 0.000005
  sched_name: "StepLR"
  sched_params:
    step: *step
    gamma: 0.1